core_env_name: canoe-development
environment: dev
regions:
  us:
    - us-east-1
azs:
  us-east-1:
    - us-east-1a
    - us-east-1b
    - us-east-1c

modules:
  vpc:
    vars:
      enabled: true
      cidr_block: "10.40.0.0/16"
      public_subnets:
        - "10.40.1.0/24"
      private_subnets:
        - "10.40.11.0/24"
        - "10.40.12.0/24"
        - "10.40.13.0/24"
      enable_dns_hostnames: false
      map_public_ip_on_launch: true
      enable_nat_gateway: true
      single_nat_gateway: true
      one_nat_gateway_per_az: false
  ecs:
    vars:
      enabled: true
  ecr:
    vars:
      enabled: true
  ecs_service:
    vars:
      enabled: true
      dns_name: app
      domain: dev.canoeintelligence.com
      name: canoe
      cluster_id: some_id
      container_name: app-canoe
      ecr_repository_url: 916296359902.dkr.ecr.us-east-1.amazonaws.com/canoe-development
      task_role_arn: some_arn
      vpc_id: vpc-042eaa466a001f1cd
      health_check_matcher: "200-299,300-399,400-499"
      health_check_path: /healthcheck
      container_port: 3000
      ssl_certificate_arn: some_arn
